apiVersion: v1
kind: Namespace
metadata:
  name: java-app
  labels:
    tigera-admission-controller: enforcing
---
apiVersion: v1
kind: Namespace
metadata:
  name: attack
---
apiVersion: v1
kind: Namespace
metadata:
  name: java-client
