---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jndi-exploit
  namespace: attack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jndi-exploit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jndi-exploit
    spec:
      containers:
      - image: quay.io/jsabo/jndi-exploit:latest
        imagePullPolicy: Always
        name: jndi-exploit
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: jndi-exploit
  namespace: attack
  labels:
    service: jndi-exploit
spec:
  ports:
  - name: ldap
    port: 1389
    targetPort: 1389
    protocol: TCP
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: jndi-exploit
